ilios_swagger_index:
    path:     /doc/
    defaults: { _controller: IliosApiBundle:SwaggerDocs:index }
    methods:  [GET]

ilios_swagger_file:
    path:     /doc/swagger.yml
    defaults: { _controller: IliosApiBundle:SwaggerDocs:yaml }
    methods:  [GET]

ilios_swagger_ui:
    path:     /doc/{fileName}
    requirements:
      fileName: .*
    defaults: { _controller: IliosApiBundle:SwaggerDocs:ui }
    methods:  [GET]

ilios_api_non_entity_routes:
    resource: "@IliosApiBundle/Resources/config/non-entity-routes.yml"

ilios_api_special_routes:
    resource: "@IliosApiBundle/Resources/config/special-routes.yml"

ilios_api_get:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:Api:get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'
        id: '(?i)[a-z0-9\-]+'

ilios_api_getall:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Api:getAll }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'

ilios_api_post:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Api:post }
    methods:  [POST]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'

ilios_api_put:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:Api:put }
    methods:  [PUT]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'
        id: '(?i)[a-z0-9\-]+'

ilios_api_delete:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:Api:delete }
    methods:  [DELETE]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'
        id: '(?i)[a-z0-9\-]+'

api_bad_request:
    path:     /{url}
    defaults:
        url: null
        _controller: IliosApiBundle:BadRequest:index
    requirements:
        url: ".+"