services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ilios\ApiBundle\:
        resource: '../../*'

    Ilios\ApiBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Ilios\ApiBundle\EventListener\ValidApiObjectListener:
        arguments:
            $validApiObjects: '%ilios_api_valid_endpoints%'
        tags: [{ name: kernel.event_listener, event: kernel.controller, method: onKernelController }]

    Ilios\ApiBundle\Service\SwaggerDocBuilder:
        arguments:
            $apiVersion: '%ilios_api_version%'

    Ilios\ApiBundle\Controller\SwaggerDocsController:
        public: true
        arguments:
            $kernelRootDir: '%kernel.root_dir%'

    Symfony\Component\Serializer\SerializerInterface:
          factory:   ['Ilios\ApiBundle\Service\SerializerFactory', createSerializer]
