imports:
    - { resource: config.yml }
    - { resource: security.yml }
    - { resource: test-data-loaders.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.db"
                logging: false
                profiling: false

liip_functional_test:
  cache_sqlite_db: true
