imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    ilios_api_version: v1.27

framework:
    #esi:             ~
    #translator:      { fallbacks: ['%locale%'] }
    secret:          '%env(ILIOS_SECRET)%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%env(ILIOS_LOCALE)%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: 'iliosapi'
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: false
    assets: ~
    php_errors:
      log: true
    web_link:
      enabled: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.root_dir%/../custom/email_templates': custom_email_templates
    exception_controller:  Ilios\CoreBundle\Controller\ExceptionController:showAction

# Doctrine Configuration
doctrine:
    dbal:
        driver:   'pdo_mysql'
        host:     '%env(ILIOS_DATABASE_HOST)%'
        port:     '%env(ILIOS_DATABASE_PORT)%'
        dbname:   '%env(ILIOS_DATABASE_NAME)%'
        user:     '%env(ILIOS_DATABASE_USER)%'
        password: '%env(ILIOS_DATABASE_PASSWORD)%'
        charset:  UTF8
        server_version: '%env(ILIOS_DATABASE_MYSQL_VERSION)%'

    orm:
      auto_generate_proxy_classes: '%kernel.debug%'
      auto_mapping: true
      metadata_cache_driver:
        type: service
        id: ilios.cache
      result_cache_driver:
        type: service
        id: ilios.cache
      query_cache_driver:
        type: service
        id: ilios.cache

# Swiftmailer Configuration
swiftmailer:
    transport: '%env(ILIOS_MAILER_TRANSPORT)%'
    host:      '%env(ILIOS_MAILER_HOST)%'
    username:  '%env(ILIOS_MAILER_USER)%'
    password:  '%env(ILIOS_MAILER_PASSWORD)%'
    spool:     { type: memory }

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/':

sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: false }
    router:  { annotations: true }

security:
    encoders:
        Ilios\AuthenticationBundle\Classes\SessionUserInterface:
            algorithm: bcrypt
        ilios_legacy_encoder:
            id: Ilios\AuthenticationBundle\Form\Encoder

doctrine_migrations:
    dir_name: '%kernel.root_dir%/Resources/DoctrineMigrations'
    name: Ilios Migrations
    namespace: Ilios\Migrations

exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
        HTML.Allowed: 'a[href],br,div,dd,dl,dt,em,li,ol,p,strong,sub,sup,ul,u'

httplug:
    plugins:
        logger: ~
    clients:
        ga:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.logger']
            config:
                verify: true
                timeout: 10

happyr_google_analytics:
    tracking_id: 'INJECTED FROM Config IN TrackApiUsageListener'
    http_message_factory: 'httplug.message_factory'
