ilios_authentication.login:
    path:     /login
    defaults: { _controller: IliosAuthenticationBundle:Authentication:login }
ilios_authentication.logout:
    path:     /logout
    defaults: { _controller: IliosAuthenticationBundle:Authentication:logout }
ilios_authentication.whoami:
    path:     /whoami
    defaults: { _controller: IliosAuthenticationBundle:Authentication:whoami }
ilios_authentication.token:
    path:     /token
    defaults: { _controller: IliosAuthenticationBundle:Authentication:token }
ilios_authentication.invalidate_tokens:
    path:     /invalidatetokens
    defaults: { _controller: IliosAuthenticationBundle:Authentication:invalidateTokens }
