/applicationconfigs:
  get:
    summary: Fetch all Applicationconfigs
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: offset
        in: query
        description: Offset
        required: false
        type: integer
      - name: limit
        in: query
        description: Limit Results
        required: false
        type: integer
      - name: order_by
        in: query
        description: Order by fields.  Must by an array ie. &order_by[name]=ASC&order_by[description]=DESC
        required: false
        type: array
        items:
          type: string
      - name: filters
        in: query
        description: Filter by fields. Must be an array ie. &filters[id]=3
        required: false
        type: array
        items:
          type: string
    tags:
      - Applicationconfigs
    responses:
      '200':
        description: An array of applicationconfigs
        schema:
          type: object
          properties:
            applicationconfigs:
              type: array
              items:
                $ref: '#/definitions/Applicationconfig'
  post:
    summary: Create Applicationconfigs
    parameters:
    - name: X-JWT-Authorization
      in: header
      description: API JWT Token
      required: true
      type: string
      default: Token XXX
    - name: body
      in: body
      required: true
      schema:
          type: object
          properties:
            applicationConfigs:
              type: array
              items:
                $ref: '#/definitions/Applicationconfig'
    tags:
      - Applicationconfigs
    responses:
      '201':
        description: An array of newly created applicationconfigs
        schema:
          type: object
          properties:
            applicationconfigs:
              type: array
              items:
                $ref: '#/definitions/Applicationconfig'
      '400':
        description: Bad Request Data
      '403':
        description: Access Denied
/applicationconfigs/{id}:
  get:
    summary: Fetch a single Applicationconfig
    parameters:
    - name: X-JWT-Authorization
      in: header
      description: API JWT Token
      required: true
      type: string
      default: Token XXX
    - name: id
      in: path
      required: true
      description: id
      type: integer
    tags:
      - Applicationconfigs
    responses:
      '200':
        description: A single Applicationconfig
        schema:
          type: object
          properties:
            applicationconfigs:
              type: array
              items:
                $ref: '#/definitions/Applicationconfig'
      '404':
        description: Not found
  put:
    summary: Edit a Applicationconfig
    parameters:
    - name: X-JWT-Authorization
      in: header
      description: API JWT Token
      required: true
      type: string
      default: Token XXX
    - name: id
      in: path
      required: true
      description: id
      type: integer
    - name: body
      in: body
      required: true
      schema:
          type: object
          properties:
            applicationConfig:
              $ref: '#/definitions/Applicationconfig'
    tags:
      - Applicationconfigs
    responses:
      '200':
        description: A single Applicationconfig
        schema:
          type: object
          properties:
            applicationconfig:
              $ref: '#/definitions/Applicationconfig'
      '400':
        description: Bad Request Data
      '403':
        description: Access Denied
      '404':
        description: Not Found
  delete:
    summary: Delete a Applicationconfig
    parameters:
    - name: X-JWT-Authorization
      in: header
      description: API JWT Token
      required: true
      type: string
      default: Token XXX
    - name: id
      in: path
      required: true
      description: id
      type: integer
    tags:
      - Applicationconfigs
    responses:
      '204':
        description: Deleted Applicationconfig
      '403':
        description: Access Denied
      '404':
        description: Not Found
      '500':
        description: Failed to delete entity (usually caused by non-cascading relationships)